(function(){'use strict';const $=id=>document.getElementById(id),api=MachineWeather,data=JSON.parse($('page-data').textContent);let storage=null;try{storage=localStorage;}catch{}let saved=storage?api.load(storage):null;let sign=data.fixed||(saved&&saved.sign)||null,mode=(saved&&saved.mode)||'Arrival';
function render(message){const browse=sign||'Spark';$('selected').textContent=sign||'Choose your sign';$('sign-title').textContent=sign||'Spark · a preview';$('gift').textContent=data.signs.find(s=>s.name===browse).gift;$('override').value=sign||'';$('mode').value=mode;$('mode-note').textContent=mode+' · '+data.edition.modes[mode];$('sign-link').href='sign-'+browse.toLowerCase()+'.html';for(const [k,v]of Object.entries(data.edition.readings[browse]))$('part-'+k).textContent=v;if(message)$('status').textContent=message;}
function remember(){try{if(!storage)throw Error();api.save(storage,{sign,mode});return 'Saved on this device only. Return tomorrow.';}catch{return 'Selection works for this visit; local storage is unavailable.';}}
$('origin-form').addEventListener('submit',ev=>{ev.preventDefault();try{sign=api.assign($('origin').value);$('origin').value='';render(sign+' is your permanent sign. '+remember());$('readings').scrollIntoView();}catch(err){$('status').textContent=err.message;}});
$('override').addEventListener('change',()=>{if(!api.signs.includes($('override').value))return;sign=$('override').value;render('Manual override: '+sign+'. '+remember());});
$('mode').addEventListener('change',()=>{mode=$('mode').value;render('Mode changed; your sign stays '+(sign||'unassigned')+'. '+(sign?remember():''));});
$('clear').addEventListener('click',()=>{try{if(storage)api.reset(storage);}catch{}sign=null;mode='Arrival';$('origin').value='';$('origin-kind').selectedIndex=0;render('Local selection cleared. No origin date was retained.');});
const today=new Date().toISOString().slice(0,10);if(data.edition.date!==today)$('freshness').textContent='Archive / stale for today: this edition is '+data.edition.date+'. Check Today for the latest published edition. No new reading is invented in your browser.';
render(saved?'Welcome back. Your saved sign is '+saved.sign+'.':null);
})();
